// File generated by FlutterFire CLI.
// ---------------------------------------------------------------------
// Android values below are filled in from this project's
// google-services.json (package: com.example.feedback_review_app).
//
// Web and iOS are still placeholders — only fill those in if you plan
// to run this app on web or iOS. To do that, register a Web/iOS app
// in Firebase Console → Project Settings → Your apps, and copy the
// matching values in.
// ---------------------------------------------------------------------

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run `flutterfire configure` to generate real options.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    authDomain: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmM8SUKSOYPafciQKbL88NprAOA_3mF2Y',
    appId: '1:9008015851:android:ca67c19a7d4846a383d1ae',
    messagingSenderId: '9008015851',
    projectId: 'fir-series-9f2d6',
    storageBucket: 'fir-series-9f2d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
    iosBundleId: 'com.example.feedbackReviewApp',
  );
}
